teachers_portal/accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

teachers_portal/base/urls.py
from django.urls import path
from .views import ClassroomListView, ClassroomDetailView, ClassroomCreateView, StudentDetail, StudentCreateView, ClassroomDeleteView, CommentPost


urlpatterns = [
    path("classroom/new/", ClassroomCreateView.as_view(), name="classroom_new"),
    path("classroom/<int:pk>/", ClassroomDetailView.as_view(), name="classroom_detail"),
    path("classroom/<int:pk>/delete/", ClassroomDeleteView.as_view(), name="classroom_delete"),
    path("classroom/student/<int:pk>/", StudentDetail.as_view(), name="student_detail"),
    path("classroom/student/new/", StudentCreateView.as_view(), name="student_new"),
    path("", ClassroomListView.as_view(), name="home"),

]

teachers_portal/teachers_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("base.urls")),
]

teachers_portal/accounts/models.py
from django.db import models

# Create your models here.

teachers_portal/base/models.py
from django.db import models
from django.urls import reverse


# Database Information

class Classroom(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("classroom_detail", kwargs={"pk": self.pk})


class Student(models.Model):
    name = models.CharField(max_length=255)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)

    class Meta:
        ordering = ["name"]  # presents students in alphabetical order

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("classroom_detail", kwargs={"pk": self.classroom.pk})


class Comment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    comment = models.TextField(max_length=255)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("student_detail")

teachers_portal/base/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)
        widgets = {
            'comment': forms.TextInput(attrs={'placeholder': 'Add a New Comment'}),
        }

teachers_portal/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

teachers_portal/base/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import SingleObjectMixin
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from .forms import CommentForm
from .models import Classroom, Student, Comment


# Classroom Views.
class ClassroomListView(LoginRequiredMixin, ListView):
    model = Classroom
    template_name = "home.html"


class ClassroomDetailView(LoginRequiredMixin, DetailView):
    model = Classroom
    template_name = "classroom_detail.html"


class ClassroomCreateView(LoginRequiredMixin, CreateView):
    model = Classroom
    template_name = "classroom_new.html"
    fields = ("title", "body")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ClassroomDeleteView(LoginRequiredMixin, DeleteView):
    model = Classroom
    template_name = "classroom_delete.html"
    success_url = reverse_lazy("home")


################################## Student Views Start ########################################
class StudentDetail(DetailView):
    # Student View is going to handle both POST and GET request to allow comments in
    model = Student
    template_name = "student_detail.html"

    # Get Request Method
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student = self.get_object()
        context["form"] = CommentForm()
        context['classroom'] = student.classroom
        return context

    # Post Reques Method
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.student = self.object
            comment.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            context = self.get_context_data(form=form)
            return self.render_to_response(context)

    def get_success_url(self):
        return reverse("student_detail", kwargs={"pk": self.object.pk})


class StudentCreateView(CreateView):
    model = Student
    template_name = "student_new.html"
    fields = ("name", "classroom",)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentPost(SingleObjectMixin, FormView):
    model = Student
    form_class = CommentForm
    template_name = "student_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.student = self.object
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        student = self.object
        return reverse("student_detail", kwargs={"pk": student.pk})

teachers_portal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Teacher Portal{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <header class="p-3 mb-3 border-bottom">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a class="navbar-brand" href="{% url 'home' %}">Teacher's Portal</a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        {% if user.is_authenticated %}
        <li><a href="{% url 'classroom_new' %}" class="nav-link px-2 link-dark">+ Add a New Classroom</a></li>
      </ul>
      <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          {{ user.username }}
        </a>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
          <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
          <li>
            <!-- Begin form for logout -->
            <form method="post" action="{% url 'logout' %}" style="margin: 0;">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">
                Log Out
              </button>
            </form>
            <!-- End form for logout -->
          </li>
        </ul>
      </div>
      {% else %}
      </ul>
      <div class="text-end">
        <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log In</a>
        <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
      </div>
      {% endif %}
    </div>
  </header>
  <main>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </main>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

teachers_portal/templates/classroom_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ classroom.title }}"?</p>
<button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

teachers_portal/templates/classroom_detail.html
{% extends "base.html" %}

{% block title %}Classrooms{% endblock title %}

{% block content %}
<h1> {{ classroom.title }} </h1>

<div class="list-group">
    {% for student in classroom.student_set.all %}
        <a href="{% url 'student_detail' pk=student.pk %}" class="list-group-item list-group-item-action">{{ student.name }}</a>
    {% endfor %}
</div>
<hr width="100%" size="2">
<a class="btn btn-primary" href="{% url 'student_new' %}" role="button">New Student</a>


<div>
    <br>
<p>
<a href="{% url 'classroom_delete' classroom.pk %}">Delete</a>
</p>
<p>Back to <a href="{% url 'home' %}">All Classrooms</a>.</p>
</div>
{% endblock content %}

teachers_portal/templates/classroom_new.html
<!-- templates/post_new.html -->
{% extends "base.html" %}
{% block content %}
<h1>New Classroom</h1>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>
{% endblock content %}

teachers_portal/templates/home.html
{% extends "base.html" %}

{% block content %}
    {% for classroom in classroom_list %}
    <div class="post-entry">
        <h2><a href="{{ classroom.get_absolute_url }}">{{ classroom.title }}</a></h2>
        <p>{{ classroom.body }}</p>
    </div>
    {% endfor %}
{% endblock content %}

teachers_portal/templates/student_detail.html
{% extends "base.html" %}
{% block content %}
<h2>{{student.name}}</h2>
<hr>
{% for comment in student.comment_set.all %}
        {{ comment.created|date:"Y-F j" }} : {{comment}}  <br>
{%endfor%}
<hr>
<form method="POST" class="row g-3">
  {% csrf_token %}
  <div class="col-auto">
    {{form}}
  </div>
  <div class="col-auto">
    <button type="submit" class="btn btn-primary mb-3">Submit Comment</button>
  </div>
</form>
<p>Back to <a href="{% url 'classroom_detail' pk=classroom.pk %}">All Students</a>.</p>
{% endblock content %}

teachers_portal/templates/student_new.html
<!-- templates/post_new.html -->
{% extends "base.html" %}
{% block content %}
<h1>New Student</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}